// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIulOnPSb2iq5ewXBj1gO_pr-l5Y07IYQ',
    appId: '1:308763659568:android:c1a5266a35b55993b18cf5',
    messagingSenderId: '308763659568',
    projectId: 'money-manager-3a90b',
    databaseURL: 'https://money-manager-3a90b-default-rtdb.firebaseio.com',
    storageBucket: 'money-manager-3a90b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0z3wjHKaMnTWJSHNp2Fkp0ACClNRnl-g',
    appId: '1:308763659568:ios:b7ebba7645d0873fb18cf5',
    messagingSenderId: '308763659568',
    projectId: 'money-manager-3a90b',
    databaseURL: 'https://money-manager-3a90b-default-rtdb.firebaseio.com',
    storageBucket: 'money-manager-3a90b.firebasestorage.app',
    iosClientId: '308763659568-9gb39i67tiv7srtjaodr12hsd4ak8kg7.apps.googleusercontent.com',
    iosBundleId: 'com.example.cloudMessagingFirebase',
  );

}